CMSProject/Areas/Admin/Models/LicentaViewModel.cs
using CMSRPPF.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMSRPPF.Areas.Admin.Models
{
    public class LicentaViewModel
    {

        public LicentaViewModel()
        {
        }

        public LicentaViewModel(LicentaDTO row)
        {
            Id = row.Id;
            Title = row.Title;
            Content = row.Content;
            UserId = row.UserId;
            Created = row.Created;
            Edited = row.Edited;
            User = row.User;

        }

        public int Id { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Content { get; set; }

        [Display(Name = "Created on")]
        public DateTime? Created { get; set; }


        [Display(Name = "Last edited")]
        public DateTime? Edited { get; set; }
        public virtual ApplicationUser User { get; set; }

        [Display(Name = "Author")]
        public string UserId { get; set; }

    }


    [Table("Licenta")]
    public class LicentaDTO
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        [Display(Name = "Created on")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm }", ApplyFormatInEditMode = true)]
        public DateTime? Created { get; set; }

        [Display(Name = "Last edited")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm }", ApplyFormatInEditMode = true)]
        public DateTime? Edited { get; set; }

        public virtual ApplicationUser User { get; set; }

        [Display(Name = "Author")]
        public string UserId { get; set; }

    }
}

CMSProject/Areas/Admin/Controllers/LicentaController.cs
using CMSRPPF.Areas.Admin.Models;
using CMSRPPF.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMSRPPF.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator, Moderator, Operator")]
    public class LicentaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Noutati
        public ActionResult Index()
        {
            List<LicentaViewModel> list;

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                // Init the list
                list = db.Licenta.ToArray().OrderByDescending(i => i.Created).Select(x => new LicentaViewModel(x)).ToList();
            }

            return View(list);
        }

        [Authorize(Roles = "Moderator")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        
        [Authorize(Roles = "Moderator")]
        [HttpPost]
        public ActionResult Create(LicentaViewModel model)
        {
            // Check model state
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                LicentaDTO dto = new LicentaDTO();

        

                // DtO Title
                dto.Title = model.Title;
               

                //Make sure title and slug are unique
                if (db.Licenta.Any(x => x.Title == model.Title))
                {
                    ModelState.AddModelError("", "That title already exists.");
                    return View(model);

                }
                //DTO the rest


                dto.Content = model.Content;
                dto.UserId = User.Identity.GetUserId();
                dto.Created = DateTime.Now;
      
                //Save DTO
                db.Licenta.Add(dto);

                db.SaveChanges();


            }
            //Set TempData message
            TempData["SMM"] = "You have added a new event!";

            //Redirect
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Moderator")]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            // Declare pageVM
            LicentaViewModel model;

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                // Get the page
                LicentaDTO dto = db.Licenta.Find(id);

                // Confirm page exists
                if (dto == null)
                {
                    return Content("The post does not exist.");
                }

                // Init pageVM
                model = new LicentaViewModel(dto);
            }

            // Return view with model
            return View(model);
        }


        [Authorize(Roles = "Moderator")]
        [HttpPost]
        public ActionResult Edit(LicentaViewModel model)
        {

            // Check model state
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (ApplicationDbContext db = new ApplicationDbContext())
            {

                // Get page id
                int id = model.Id;

                // Get the page
                LicentaDTO dto = db.Licenta.Find(id);
                
                // DTO the title
                dto.Title = model.Title;


                // Make sure title and slug are unique
                if (db.Licenta.Where(x => x.Id != id).Any(x => x.Title == model.Title))
                {
                    ModelState.AddModelError("", "That title already exists.");
                    return View(model);
                }

                // DTO the rest
                dto.Content = model.Content;
                dto.Edited = DateTime.Now;

                // Save the DTO
                db.SaveChanges();
            }

            // Set TempData message
            TempData["SMM"] = "You have edited the post!";

            // Redirect
            return RedirectToAction("Index");
        }



        [Authorize(Roles = "Moderator")]
        public ActionResult Details(int id)
        {
            // Declare PageVM
            LicentaViewModel model;

            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                // Get the page
                LicentaDTO dto = db.Licenta.Find(id);

                // Confirm page exists
                if (dto == null)
                {
                    return Content("The post does not exist.");
                }


                // Init PageVM
                model = new LicentaViewModel(dto);
            }

            // Return view with model
            return View(model);
        }

        [Authorize(Roles = "Moderator")]
        public ActionResult Delete(int id)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                // Get the page

                LicentaDTO dto = db.Licenta.Find(id);
               
                // Remove the page
                db.Licenta.Remove(dto);

                // Save
                db.SaveChanges();
            }

            // Redirect
            return RedirectToAction("Index");
        }

    }
}

CMSProject/Controllers/AcademicController.cs
using CMSRPPF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMSRPPF.Controllers
{
    public class AcademicController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Academic
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Licenta()
        {
            return View(db.Licenta.OrderByDescending(i => i.Created).ToList());
        }

        public ActionResult Masterat()
        {
            return View();
        }
    }
}

CMSProject/Views/Academic/Index.cshtml
@{
    ViewBag.Title = "";
}



<div data-aos="fade-up"  class="container"  style="margin-bottom:50px; margin-top:50px">

    <!-- Three columns of text below the carousel -->
    <div class="row" style="padding-bottom:25px;">
        <div class="col-lg-6 text-center">

            <a href="@Url.Action("Licenta", "Academic")">
                <span class="fa-stack fa-5x zoom">
                    <i class="fa fa-circle fa-stack-2x icons"></i>
                    <i class="fa fa-star fa-stack-1x fa-inverse"></i>
                </span>
            </a>

            <h2>< Studii de Licenta /></h2>


        </div><!-- /.col-lg-4 -->
        <div class="col-lg-6 text-center">

            <a href="@Url.Action("Masterat", "Academic")">
                <span class="fa-stack fa-5x zoom ">
                    <i class="fa fa-circle fa-stack-2x icons"></i>
                    <i class="fa fa-star fa-stack-1x fa-inverse"></i>
                </span>
            </a>

            <h2>< Studii de Masterat /></h2>


        </div><!-- /.col-lg-4 -->




</div>

CMSProject/Views/Academic/Licenta.cshtml
@model IEnumerable<CMSRPPF.Areas.Admin.Models.LicentaDTO>
@{
    ViewBag.Title = "";
}

<br />
<div class="container">
    <div class="licenta">
        @foreach (var item in Model)
        {
            <div class="col-md-12" style="align-content:center">
                <div id="@item.Id" class="row list-group" style="max-width:700px; margin:auto;">

                    <div class=" grid-group-item list-group-item">

                        <h4 class="group inner list-group-item-heading">
                            @Html.DisplayFor(modelItem => item.Title)
                        </h4>
                        <p class="pull-right group inner list-group-item-text">
                            Posted on: @Html.DisplayFor(modelItem => item.Created)
                            <br />
                            @if (item.Edited != null)
                            {
                                <text>Last edited: @Html.DisplayFor(modelItem => item.Edited)</text>
                            }
                            else { }

                        </p>
                        <hr />
                        <p> @Html.Raw(item.Content) </p>



                    </div>
                    <br>

                </div>

                <br />
            </div>

        }
    </div>
</div>

CMSProject/Views/Academic/Masterat.cshtml
@{
    ViewBag.Title = "";
}

<div class="container">

    <h2>Masterat</h2>



</div>